### ISSUE TITLE
Typescript typings

### ISSUE THREAD

**Issue by arcanewater** [longztian/koa-session-minimal#2]
Hey thanks for lib as koa-generic is a bit outdated, btw using this with Postgres is same with this lib + koa-pg-session? Or anything else recommended? 

Also main question any possibilites for typescript 2 typings? Would be really awesome to use this with typescript

**Comment by longztian** [comment]
Hi arcanewater,

Thanks for the suggestion. I haven't gotten any experience to create type definitions for TypeScript yet. I just googled "Koa TypeScript" to find an example. It seems like [Koa 2 doesn't have TypeScript definitions](https://github.com/koajs/koa/issues/556) either. 

koa-pg-session should work well with this middleware. You can actually use any store that works with koa-generic. Because this middleware and koa-generic share the same store interfaces. I use 'koa-redis' for my personal projects.

**Comment by arcanewater** [comment]
Thanks for answer,
actually Koa have definitions https://github.com/DefinitelyTyped/DefinitelyTyped/tree/types-2.0/koa
here is browser for typings http://microsoft.github.io/TypeSearch/

**Comment by longztian** [comment]
Thanks arcanewater,
Very useful information. I should be able to create the definitions this week.

**Comment by longztian** [comment]
@arcanewater 
pull request created: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/12029
the definition files are also available in my fork: https://github.com/longztian/DefinitelyTyped/tree/master/koa-session-minimal

**Comment by longztian** [comment]
definitions merged to main repo https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/koa-session-minimal
