### ISSUE TITLE
occur a waring

### ISSUE THREAD

**Issue by yuu2lee4** [longztian/koa-session-minimal#4]
i use it with koa-generic-session-mongo like this:
app.use(session({
        cookie: {maxAge: 1000 * 60 * 60 * 24 * 30},//30 days
        store: new MongoStore()
  }))

when i set: ctx.session.user = user , the shell tell me:
(node:12780) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): TypeError: Cannot read property 'maxAge' of undefined

node version: 7.2.0

**Comment by longztian** [comment]
Hi yuu2lee4,

I think this may be caused by an obsolete store interface implemented by `koa-generic-session-mongo`. 
https://github.com/pavelvlasov/koa-generic-session-mongo/blob/master/src/store.js#L150

The correct interface should be `set(sid, sess, ttl): set session object for sid, with a ttl (in ms)`, for both [`koa-session-minimal`](https://github.com/longztian/koa-session-minimal#session-store) and [`koa-generic-session`](https://github.com/koajs/generic-session#session-store).

It works for `koa-generic-session` because `koa-generic-session` stores a copy of cookie options in each session record in database, which is explicitly removed by  `koa-session-minimal`, because we believe that [cookie options are not session data](https://github.com/koajs/generic-session/issues/72).

I will create an Issue for  `koa-generic-session-mongo`.

**Comment by longztian** [comment]
There is already [an Issue opened](https://github.com/pavelvlasov/koa-generic-session-mongo/issues/14). I will update that one.

**Comment by longztian** [comment]
`set` interface has been updated in `koa-generic-session-mongo`
