### ISSUE TITLE
cicyle dependecies

### ISSUE THREAD

**Issue by yuu2lee4** [longztian/koa-session-minimal#5]
when i use koa-generic-session-mongo with koa-session-minimal in koa2, it tell me cicyle dependecies
![image](https://cloud.githubusercontent.com/assets/8046366/21072377/2650f2b2-befb-11e6-861d-bc7f85bd1746.png)
this is my app.js:
![image](https://cloud.githubusercontent.com/assets/8046366/21072380/4cb36138-befb-11e6-8549-4e437fe0d9cd.png)
and  i just get a user from mongodb , and set it to session.user:
![image](https://cloud.githubusercontent.com/assets/8046366/21072383/650a7654-befb-11e6-93de-fc93e875009e.png)
 my node version is 7.2.1,and i use it with --harmony to handle async function.

**Comment by longztian** [comment]
Hi yuu2lee4,

nothing indicates that this is a session middleware issue. I created a simple test example with mongo store and tested with node/v7.2.1 with --harmony options. The session works fine. Can you test with [example/07_mongodb_store.js](https://github.com/longztian/koa-session-minimal/blob/master/example/07_mongodb_store.js)

Here is the shell output for my test:
```bash
# clone repo
ikki@dev:/tmp$ **git clone https://github.com/longztian/koa-session-minimal.gitCloning into 'koa-session-minimal'**
remote: Counting objects: 388, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 388 (delta 1), reused 0 (delta 0), pack-reused 381
Receiving objects: 100% (388/388), 68.37 KiB | 0 bytes/s, done.
Resolving deltas: 100% (245/245), done.

ikki@dev:/tmp$ **cd koa-session-minimal/**

# install dependencies
ikki@dev:/tmp/koa-session-minimal$ **npm install**

... ...

# node version
ikki@dev:/tmp/koa-session-minimal$ **node -v**
v7.2.1

# build dist and run tests
ikki@dev:/tmp/koa-session-minimal$ **make** 

# mongodb record before running example
ikki@dev:/tmp/koa-session-minimal$ **echo 'db.sessions.find()' | mongo**
MongoDB shell version: 2.6.12
connecting to: test
{ "_id" : ObjectId("584c639b40a525d58ea26ae9"), **"count" : 12**, "sid" : "koa:sess:eGyFRjiJ0TwJykty_0-RNJG4sR9itXSg", "ttl" : ISODate("2016-12-11T20:56:05.598Z") }
bye

# start example server and visit localhost:3000 from a browser
ikki@dev:/tmp/koa-session-minimal$ **node --harmony example/07_mongodb_store.js** 
^C

# mongodb record after running example
ikki@dev:/tmp/koa-session-minimal$ **echo 'db.sessions.find()' | mongo**
MongoDB shell version: 2.6.12
connecting to: test
{ "_id" : ObjectId("584c639b40a525d58ea26ae9"), **"count" : 15**, "sid" : "koa:sess:eGyFRjiJ0TwJykty_0-RNJG4sR9itXSg", "ttl" : ISODate("2016-12-11T20:58:06.751Z") }
bye

```

**Comment by longztian** [comment]
Hi yuu2lee4,

I just got a hint from [this ticket](https://github.com/koajs/generic-session/issues/106). The error message showed that bson library could not serialize the data (before putting it into MongoDB session collection). The `user` is a MongoDB `document` which may be deeply bond to a MongoDB record in the database. Now since you were using mongo store as your session store, you were trying to save a document from the user collection into the session collection. I guess the mongo store also use `bson` to serialize data, then it hit a circular serialization when trying to serialize some internal data of your `user` object.

You can either use a different session store, or convert your `user` object to a plain javascript object (with any fields you want to keep) and save it to `ctx.session.user`. like below:
```javascript
ctx.session.user = {
    id: user._id,
    name: user.name,
}
```

I prefer the second way. So that you know exactly what kind of data (after serialization) is saved to your session store. Let me know if this works for you.

**Comment by yuu2lee4** [comment]
many tks, the second way is worked
